name: Analyze SonarQube Report with GPT-4

on:
  workflow_dispatch:

jobs:
  gpt-analysis:
    runs-on: ubuntu-latest
    name: Summarize SonarQube Issues with Azure OpenAI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download SonarQube Report
        uses: actions/download-artifact@v4
        with:
          name: sonar-report
          path: report/

      - name: Run Azure Function for GPT-4 Summary
        run: |
          curl -s -X POST "${{ secrets.AZURE_FN_ENDPOINT }}" \
               -H "Content-Type: application/json" \
               --data-binary @report/sonar_issues.json > summary.md

      - name: Upload GPT Summary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-gpt-summary
          path: summary.md
