name: Frontend SAST Scan

on:
  workflow_call:

jobs:
  frontend-sast:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: |
          cd frontend
          npm ci
          npm run build
          mkdir -p reports
          npx sonar-scanner -Dsonar.projectKey=my-frontend -Dsonar.sources=src -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
          curl -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/issues/search?componentKeys=my-frontend&ps=500" -o reports/sonar-report.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - uses: actions/upload-artifact@v3
        with:
          name: sonar-report-frontend
          path: reports/sonar-report.json
