name: Backend SAST Scan

on:
  workflow_call:

jobs:
  backend-sast:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet sonarscanner begin /k:"my-backend" /d:sonar.host.url=$SONAR_HOST_URL /d:sonar.login=$SONAR_TOKEN
          dotnet build
          dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
          mkdir -p reports
          curl -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/issues/search?componentKeys=my-backend&ps=500" -o reports/sonar-report.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - uses: actions/upload-artifact@v3
        with:
          name: sonar-report-backend
          path: reports/sonar-report.json
