name: Summarize SonarQube Reports with GPT-4

on:
  workflow_call:

jobs:
  summarize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        report: [sonar-report-backend, sonar-report-frontend]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.report }}
          path: reports

      - run: pip install openai

      - name: Summarize report using GPT-4 (Azure OpenAI)
        run: |
          import openai, os, json
          client = openai.AzureOpenAI(
              api_key=os.getenv("AZURE_OPENAI_API_KEY"),
              azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
              api_version="2023-05-15"
          )
          with open('reports/sonar-report.json') as f:
              issues = json.load(f).get("issues", [])
          prompt = f"""You are a security expert. Analyze this SonarQube scan report and list the 5 most critical security issues with suggestions.

          {json.dumps(issues[:10], indent=2)}"""
          response = client.chat.completions.create(
              model=os.getenv("AZURE_OPENAI_DEPLOYMENT"),
              messages=[
                  {"role": "system", "content": "You are a senior code security reviewer."},
                  {"role": "user", "content": prompt}
              ],
              temperature=0.3,
              max_tokens=1000
          )
          print(f"\n✅ GPT-4 Summary for {os.getenv('GITHUB_WORKFLOW')}:\n{response.choices[0].message.content}")
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
        shell: python
