name: SonarQube Scan + GPT-4 Summarize (Clean)

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  sonarqube-genai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenAI Python SDK
        run: pip install openai

      - name: Run GPT-4 Summary on SonarQube Report
        env:
          OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          OPENAI_API_BASE: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
        run: |
          python3 <<EOF
          import openai
          import os
          import json

          # New Client usage (openai v1.0+)
          client = openai.AzureOpenAI(
              api_key=os.environ["OPENAI_API_KEY"],
              azure_endpoint=os.environ["OPENAI_API_BASE"],
              api_version="2023-05-15"
          )

          # Read dummy report (adjust path if needed)
          with open("reports/sonar-report.json") as f:
              issues = json.load(f).get("issues", [])

          prompt = f"""Summarize this SonarQube report. Focus on critical vulnerabilities, suggest best practices and possible fixes.

          {json.dumps(issues[:10], indent=2)}"""

          completion = client.chat.completions.create(
              model=os.environ["OPENAI_DEPLOYMENT"],
              messages=[
                  {"role": "system", "content": "You are a senior secure code reviewer."},
                  {"role": "user", "content": prompt}
              ],
              temperature=0.3,
              max_tokens=1000
          )

          print("\n✅ GPT-4 Summary:\n")
          print(completion.choices[0].message.content)
          EOF
