name: Upload Dummy Sonar Report

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create sonar-report.txt
        run: |
          echo "Remove the unused private field '_unusedField'.\nUnreachable code detected.\nUnused variable 'password'.\nMethod can be marked as static." > sonar-report.txt

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report
          path: sonar-report.txt
